// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwRScmRAdX1Sv9Go_qjeVXpZkFrzLtvow',
    appId: '1:736035685341:web:c220093dc935a7c842ac34',
    messagingSenderId: '736035685341',
    projectId: 'insta-8109f',
    authDomain: 'insta-8109f.firebaseapp.com',
    storageBucket: 'insta-8109f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVkIcbz1pgwX4PxIMgt0k1UlbEIbNYKY4',
    appId: '1:736035685341:android:c3548aa367c9f6ef42ac34',
    messagingSenderId: '736035685341',
    projectId: 'insta-8109f',
    storageBucket: 'insta-8109f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFLfMSKwlZwqdQeS791WdcRes6jI52dwY',
    appId: '1:736035685341:ios:ac1bc9f8b0783d2342ac34',
    messagingSenderId: '736035685341',
    projectId: 'insta-8109f',
    storageBucket: 'insta-8109f.firebasestorage.app',
    iosBundleId: 'com.example.instagramApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFLfMSKwlZwqdQeS791WdcRes6jI52dwY',
    appId: '1:736035685341:ios:ac1bc9f8b0783d2342ac34',
    messagingSenderId: '736035685341',
    projectId: 'insta-8109f',
    storageBucket: 'insta-8109f.firebasestorage.app',
    iosBundleId: 'com.example.instagramApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwRScmRAdX1Sv9Go_qjeVXpZkFrzLtvow',
    appId: '1:736035685341:web:9aff8e2876752dc642ac34',
    messagingSenderId: '736035685341',
    projectId: 'insta-8109f',
    authDomain: 'insta-8109f.firebaseapp.com',
    storageBucket: 'insta-8109f.firebasestorage.app',
  );

}